name: Issue moderator

on:
  issues:
    types: [ opened, edited, reopened ]
  issue_comment:
    types: [ created ]

jobs:
  autoclose:
    runs-on: ubuntu-latest
    steps:
      - name: Moderate issues
        uses: keiyoushi/issue-moderator-action@a017be83547db6e107431ce7575f53c1dfa3296a
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          duplicate-label: Duplicate

          blurbs: |
            [
              {
                "keywords": ["cf", "cloudflare"],
                "message": "Refer to the **Solving Cloudflare issues** section at https://komikku-repo.github.io/docs/guides/troubleshooting#cloudflare. If it doesn't work, migrate to other sources or wait until they lower their protection."
              },
              {
                "keywords": ["uninstall"],
                "message": "Uninstall the extension before updating. If that does not work, uninstall it from your device's settings by navigating to your device's Settings -> Apps and uninstall it from there by looking for `Tachiyomi: <extension name>`.\n\nThis is usually caused your previous extension having a different signature from the updated extension, making Android refuse to update it."
              }
            ]

          duplicate-check-enabled: true
          duplicate-check-labels: |
            ["Source request", "Domain changed"]

          existing-check-enabled: true
          existing-check-labels: |
            ["Source request", "Domain changed"]
          existing-check-repo-url: https://raw.githubusercontent.com/komikku-app/tracker-extensions/repo/index.min.json

          auto-close-rules: |
            [
              {
                "type": "body",
                "regex": ".*DELETE THIS SECTION IF YOU HAVE READ AND ACKNOWLEDGED IT.*",
                "message": "The acknowledgment section was not removed."
              },
              {
                "type": "body",
                "regex": ".*\\* (Tachiyomi version|Android version|Device): \\?.*",
                "message": "Requested information in the template was not filled out."
              },
              {
                "type": "title",
                "regex": ".*(Source name|Short description).*",
                "message": "You did not fill out the description in the title."
              },
              {
                "type": "both",
                "regex": ".*(?:fail(?:ed|ure|s)?|can\\s*(?:no|')?t|(?:not|un).*able|(?<!n[o']?t )blocked by|error) (?:to )?(?:get past|by ?pass|penetrate)?.*cl[oa]ud ?fl?[ai]re.*",
                "ignoreCase": true,
                "labels": ["Cloudflare protected"],
                "message": "Refer to the **Solving Cloudflare issues** section at https://komikku-repo.github.io/docs/guides/troubleshooting#cloudflare. If it doesn't work, migrate to other sources or wait until they lower their protection."
              }
            ]
          auto-close-ignore-label: do-not-autoclose
